#!/bin/sh
    ssh ubuntu@ec2-18-222-52-53.us-east-2.compute.amazonaws.com <<EOF
    sudo su - malhotra
    cd ~/nextjs-nodejs
    git checkout staging
    rm -rf package-lock.json
    rm -rf .next
    git pull origin staging
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v10.11.0
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js 
    exit
EOF